server:
  tomcat:
    # 配置Tomcat的访问日志
    accesslog:
      enabled: true
    # 指定Tomcat的发布目录
    basedir: target/tomcat
  servlet:
    # 指定服务器的内容根路径
    context-path: /cloud-collect/api

spring:
  jpa:
    # 表不存在时自动创建，之后更新
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    username: Windea
    password: BreezesLanding
    url: jdbc:mysql://localhost:3306/cloud_collect
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        # 不使用SSL，否则结束应用时会报错SSLException
        useSSL: false
        # 配置数据库的时区，否则会报错
        serverTimezone: GMT+8
        # 允许使用服务器提供的公钥
        allowPublicKeyRetrieval: true
    tomcat:
      db-properties:
        close-method: close
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  jackson:
    serialization:
      # 防止json序列化时出错，非常重要！
      fail-on-empty-beans: false

### 以下是自定义配置

com:
  windea:
    security:
      jwt:
        # jwt口令的请求头
        tokenHeader: Authorization
        # jwt口令的开头
        tokenHead: Bearer
        # jwt密钥
        secret: com.windea
        # jwt过期时间
        expiration: 86400
    validation:
      username:
        # 6~16位的字母、数字和下划线，以字母开头。
        validRegex: "\\w{6,16}"
      password:
        # 6~16位的字母、数字和下划线。
        validRegex: "[a-zA-Z]\\w{5,15}"
    ie:
      # 缓存文件路径
      tempPath: D:/CloudCollect/temp
      # 数据文件文件名
      dataSchemaFileName: dataSchema
