spring:
  application:
    name: cloud-collect-demo
  main:
    allow-bean-definition-overriding: true
  #  data:
  #    redis:
  #      repositories:
  #        enabled: false
  datasource:
    username: Windea
    password: BreezesLanding
    url: jdbc:mysql://localhost:3306/cloud_collect
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        # 不使用SSL，否则结束应用时会报错SSLException
        useSSL: false
        # 配置数据库的时区，否则会报错
        serverTimezone: GMT+8
        # 允许使用服务器提供的公钥
        allowPublicKeyRetrieval: true
    tomcat:
      db-properties:
        close-method: close
  jackson:
    serialization:
      # 防止json序列化时出错，非常重要！
      fail-on-empty-beans: false
  #  redis:
  #    # Redis数据库索引（默认为0）
  #    database: 0
  #    # Redis服务器地址
  #    host: localhost
  #    # Redis服务器连接端口
  #    port: 6379
  #    # Redis服务器连接密码（默认为空）
  #    password: ""
  #    lettuce:
  #      pool:
  #        # 连接池最大连接数（使用负值表示没有限制） 默认 8
  #        max-active: 8
  #        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
  #        max-wait: -1
  #        # 连接池中的最大空闲连接 默认 8
  #        max-idle: 8
  #        # 连接池中的最小空闲连接 默认 0
  #        min-idle: 0
  mail:
    host: smtp.qq.com
    username: dk_breeze@qq.com
    password: dpkqsdjhbbwidhec
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

server:
  tomcat:
    # 配置Tomcat的访问日志
    accesslog:
      enabled: true
    # 指定Tomcat的发布目录
    basedir: target/tomcat
  servlet:
    # 指定服务器的内容根路径
    context-path: /cloud-collect/api

com:
  windea:
    config:
      require-activate: false
      send-email: false
    security:
      jwt:
        token-header: Authorization
        token-head: Bearer
        secret: com.windea
        expiration: 86400
    validation:
      username: "\\w{6,16}"
      password: "[a-zA-Z]\\w{5,15}"
    data-import-export:
      path: D:/CloudCollect
      data-file-name: dataSchem

#logging:
#  level:
#    org.springframework: debug
